# Build Image
FROM node:8 as build-step1



RUN mkdir -p /school
WORKDIR /school

COPY ./package.json package-lock.json ./school/
#RUN npm install --force
#RUN npm install --save-dev @angular-devkit/build-angular
#RUN npm install -g npm@10.2.4
COPY . .
RUN npm install -g @angular/cli@8
#RUN npm install --verbose --save-dev @angular-devkit/build-angular

RUN npm i

#WORKDIR ./nibss1/

COPY . /school/
#RUN npm install
RUN npm install --save-dev @angular-devkit/build-angular
RUN  ng build --prod
#RUN ng build --configuration=production
#COPY --from=build-step1 web.config /home/ebills-admin/current-frontend/Ebills-Frontend/ebills-admin-app /nibss-admin/dist/ebills-admin
#

FROM nginx:1.17.1-alpine



COPY --from=build-step1 /school/dist  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
